import sqlalchemy as sa

from alembic import op

from lib.util_datetime import tzware_datetime
from lib.util_sqlalchemy import AwareDateTime
from sqlalchemy.dialects import postgresql

"""
Add foobar column to users

Revision ID: 55de4f57a342
Revises: fd714cf06748
Create Date: 2020-02-04 11:22:02.386817
"""

# Revision identifiers, used by Alembic.
revision = '55de4f57a342'
down_revision = 'fd714cf06748'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('foobar', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_users_foobar'), 'users', ['foobar'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_foobar'), table_name='users')
    op.drop_column('users', 'foobar')
    ### end Alembic commands ###
